packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild

minimumReleaseAge: 0

allowBuilds:
  '@scarf/scarf': true
  esbuild: true
  unrs-resolver: true
